wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705415093.551452
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
k:
  desc: null
  value: 20
